version: "3"
services:
  app:
    build: ./backend
    ports:
      - "3001:5000"
    volumes:
      - ./backend:/app
    environment:
      FLASK_ENV: development
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/user/src/app
    entrypoint:
      - sh
    command:
    depends_on:
      - app
    # environment:
    #   - CHOKIDAR_USEPOLLING=true
